### ISSUE TITLE
Cannot load `Rails.config.active_storage.service`: uninitialized constant ActiveStorage::Service::QiniuService::Qiniu

### ISSUE THREAD

**Issue by lukefan** [mycolorway/activestorage_qiniu#9]
我在使用Active_Storage的时候，遇到了一个奇怪问题。
这么多年来，一直都在使用七牛云，做了设置：
storage.yml里面

```yml
qiniu:
    service: Qiniu
    access_key: <%= Rails.application.credentials.dig(:qiniu, :access_key) %>
    secret_key: <%= Rails.application.credentials.dig(:qiniu, :secret_key) %>
    bucket: <%= Rails.application.credentials.dig(:qiniu, :bucket) %>
    domain: <%= Rails.application.credentials.dig(:qiniu, :domain) %>
```

development.rb 里面

```rb
config.active_storage.service = :qiniu
```

_form.html.erb里面

```erb
 <%= form.file_field :image, direct_upload: true%>
```

在上传文件的时候，却得到了这样的提示：

```bash
NameError (Cannot load `Rails.config.active_storage.service`:
uninitialized constant ActiveStorage::Service::QiniuService::Qiniu):
```

使用local的时候，没有问题。
七牛的全套设置，是在其他项目里面一直在用的，肯定没有问题。

请问我少设置了什么吗？

当我添加了：
`rb
config.active_storage.analyzers = [ ActiveStorage::Analyzer::QiniuImageAnalyzer, ActiveStorage::Analyzer::QiniuVideoAnalyzer ]
`
之后，显示analyzers失败。
